name: test_task
version: 1.0.0+1
description: Flutter Wallpaper App.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.4.0
  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.4.1
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.10
  json_serializable: ^6.1.6

flutter:
  generate: true
  uses-material-design: true
